### ISSUE TITLE
Strawmat vanishes & Thatch(Block) missing

### ISSUE THREAD

**Issue by Raccoon2709** [Aetherial-Labs/Issue-Reporting#10]
Expected Behavior:

Strawmat are stackable OR Strawmat Error message => can't place Strawmat

Current Behavior

Strawmat vanishes ontop of the old Strawmat.

Reproduce:

Get 2x Strawmat place 1 on the ground and place another on top of it, you will lose 1 strawmat.

https://user-images.githubusercontent.com/10391092/235370942-6c64cf11-de38-4dcd-868b-3cd27cbde84d.mp4

**Comment by VinterNacht** [comment]
Will look into this on the next update.
