### ISSUE TITLE
Unbreakable Trees in Wildcraft Tree's

### ISSUE THREAD

**Issue by Raccoon2709** [Aetherial-Labs/Issue-Reporting#11]
Expected Behavior:

Tree's break when hit by tool.

Current Behavior

A tree with 2x2 in Wildcraft currently is not harvestable OR takes way to long.

Trees in question: Douglas Fir Tree

Video is to big sadly, but i cut 2 mins on it and there wasnt even an indicator it could break soon. All other trees work fine!

Another weird issue, selfplanted trees can't be cut too!

**Comment by VinterNacht** [comment]
I'm going to need a lot more information about your play environment, any other included mods, etc.  There is nothing in IDG that should be causing this independently, and I can't replicate it in the dev environment. All of this points to a conflict somewhere.
