### ISSUE TITLE
texture asset error

### ISSUE THREAD

**Issue by PhyDoesStuff** [Aetherial-Labs/Issue-Reporting#12]
I'm getting the following error in client-main.txt on world load:
`4.6.2023 11:03:29 [Warning] Texture asset 'fromgoldencombs:textures/block/beehive/wax.png' not found (defined in Baked variant of block fromgoldencombs:hivetop-empty).`

Looking in the mod's files, I can see assets/fromgoldencombs/textures/block/beehive/beeswax.png, so I'd guess it's just a naming issue.

**Comment by VinterNacht** [comment]
Will confirm before closing, but believe this is corrected in upcoming release.

**Comment by VinterNacht** [comment]
Corrected a while ago, closing issue.
