### ISSUE TITLE
Dev1 not loading

### ISSUE THREAD

**Issue by LocoMinerDad** [Aetherial-Labs/Issue-Reporting#13]
Dev 1 dapple gloves is seen in my mod list when the game loads nothing from the mod is present, ? blocks everywhere, and nothing is in the handbook. Dev 1 requires net7 to work

**Comment by LocoMinerDad** [comment]
Chopping and cutting block seems to be fixed, uses a stack of logs in each, 
and nothing disappeared. 
Axes still aren't used in recipes 
Existing player planted trees don't have roots
Player place sapling before and after update produce roots.
Weak Tannin works, heavy doesn't

**Comment by VinterNacht** [comment]
"Existing player planted trees don't have roots
Player place sapling before and after update produce roots." 
-> Existing trees will not get roots. This is working as expected.

"Axes still aren't used in recipes" -> Not sure how to handle this compatibility. I don't use every mod and don't have time to go through and locate which need it and build in compatibility.  This might wind up being a community project.

"Weak Tannin works, heavy doesn't" - I'll look into this and confirm. Can you provide more info about what it means for "Heavy Tannin" to not work? I need more specifics.

**Comment by LocoMinerDad** [comment]
I put in dried bark into a barrel with weak tannin, and it doesn't say it will turn into strong tannin.

**Comment by VinterNacht** [comment]
Determined it was .Net4 vs .Net7 issue.
