### ISSUE TITLE
Ceramic hives broken

### ISSUE THREAD

**Issue by NezcalSpindrake** [Aetherial-Labs/Issue-Reporting#18]
Recently updated from 1.18.7 to 1.18.15 and updated a lot of mods as such, including From Golden Combs. The ceramic hives I had placed (empty, only finally made them in winter) and placed a honey pot on have all gotten weird. They appear to have the hitbox as though they have a honey pot, but do not relinquish the honey pot when right clicked. In addition, when they are broken by hand (as they also cannot be picked up, even into a backpack slot) they vanish, but are still present, as attempting to place another block in their space makes them reappear. Attempting to place the honey pot on them either places it above it in another block space, or says there is another block in the way.
If it matters, partway through the updating process the mod failed to load at one point and they were question blocks that said they were ceramic hive with honey pot (whatever the block ID for them is).

**Comment by VinterNacht** [comment]
This is unusual, I wonder if it has something to do with the hives being preexisting.  Have you tried picking them up and replacing them rather than breaking them?  Are they all from before your update?

**Comment by NezcalSpindrake** [comment]
They are all from before the update. I said in the original post that I can't pick them up into a backpack slot (don't blame you for missing it, that was a word salad). New hives created and placed after the update work as normal.

**Comment by VinterNacht** [comment]
Hmmm... That may very well be the problem, but I'm not sure what to suggest to fix it. Were you having the same problems in the previous version?

**Comment by NezcalSpindrake** [comment]
No, they behaved normally before the update. My guess is something about their data got broken when they loaded without the mod being loaded. Unsure how to remove them, as they are in quite crucial placement in my bee room.
