### ISSUE TITLE
[1.18 rc8] Placing Beeswax in a Barrel crashes the game

### ISSUE THREAD

**Issue by Elfinlocks** [Aetherial-Labs/Issue-Reporting#2]
The log seems to claim that there is a missing texture:

https://pastebin.com/XfpxphxP

**Comment by VinterNacht** [comment]
I'm kind of expecting bugs like these to crop up.  I had to necrocode part of 1.18 from an old version of 1.17, and there's going to be little things like this that sneak in.  It's part of why the handbook is such a bloody mess.  I'll look into this tomorrow and try to get an immediate fix out.

**Comment by Elfinlocks** [comment]
Thank you so much for your help <3

**Comment by VinterNacht** [comment]
Issue Resolved in 1.18-v1.4.16-rc.1
