### ISSUE TITLE
Disapearing Honeypots, literaly.

### ISSUE THREAD

**Issue by DejFidOFF** [Aetherial-Labs/Issue-Reporting#23]
From Golden Combs 1.6.2

Honeypots are poof to air. How to replicate:

I was moving my clay hives, I had lots of empty backpack slots, but I did not have enough inventory slots (since those hives/honeypots dont stack) so when I has backpackslot selected (as you have to, to place down things from that slot) and clicked a honeypot that I had no space for in inventory, it goes poof. They were fired and used

**Comment by VinterNacht** [comment]
Resolved this. :)
