### ISSUE TITLE
In Dappled Groves Fruit Tree Crash 1.18 Stable

### ISSUE THREAD

**Issue by suspicouspickaxe** [Aetherial-Labs/Issue-Reporting#4]
Whenever I try cut a branch off a fruit tree, my game will freeze for a few seconds then just close out, I have tested it with most of the axes and the issue still persists, when I disabled the mod I was able to cut the branches off just fine, this also seems to happen with all of the fruit trees.

**Comment by VinterNacht** [comment]
So this happens specifically with branches, not with the whole tree? I'm having trouble repeating this issue, but will continue testing.

**Comment by VinterNacht** [comment]
Ok, yes. It's occurring specifically with branches... The error is *instant*.  Let me see what can be done.

**Comment by VinterNacht** [comment]
This issue has been resolved, pending further testing.
