### ISSUE TITLE
In Dappled Groves - Clay Oven can't be filled with firewood

### ISSUE THREAD

**Issue by Burgersim** [Aetherial-Labs/Issue-Reporting#7]
Hi, I just found out that I can't fill my Clay Oven with firewood anymore since I installed In Dappled Groves. It always says "The oven is full" although it's empty and shows me the tooltip for filling it by right clicking it (different tooltip btw than in the vanilla game, where it's shift and right click to fill).

It almost seems like the clay oven is somehow not registering that the firewood is actually firewood that can be used. The message "Oven is full" is the same message I get when I try to put in something that doesn't go in the oven, but I can still put in a pie for example. Maybe some attribute is missing in the firewood patch that the clay oven needs to determine that it is usable there as a heat/burn source?

**Comment by VinterNacht** [comment]
Curious... I just checked, and it seems to work fine on my machine, which isn't helpful for us in figuring out what's going on. What other mods are you running with? In Dappled Groves does not appear to be causing this effect.

**Comment by VinterNacht** [comment]
Ok, I was wrong. I was able to replicate this. I was trying to test it with the aged firewood on accident, which works fine.  Regular firewood, however, does not.

**Comment by VinterNacht** [comment]
But I fixed it in the upcoming release! \o.o/ That was quick.  Will be working in 0.4.9-rc.2
