### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by RogueRaiden** [Aetherial-Labs/Issue-Reporting#8]
Loading a fresh world, 1.18.1, InDappledGroves v0.4.9-rc.2 and get these console errors:

23.4.2023 05:16:03 [Server Warning] Failed resolving a blocks itemdrop or smeltedstack with code indappledgroves:adzehead-copper in smithing recipe indappledgroves:recipes/smithing/adzehead.jsongame:ingot-copper
23.4.2023 05:16:03 [Server Warning] Failed resolving a blocks itemdrop or smeltedstack with code indappledgroves:adzehead-gold in smithing recipe indappledgroves:recipes/smithing/adzehead.jsongame:ingot-gold
23.4.2023 05:16:03 [Server Warning] Failed resolving a blocks itemdrop or smeltedstack with code indappledgroves:adzehead-silver in smithing recipe indappledgroves:recipes/smithing/adzehead.jsongame:ingot-silver
23.4.2023 05:16:03 [Server Event] 255 smithing recipes loaded (3 could not be resolved)
23.4.2023 05:16:03 [Server Warning] Failed resolving a blocks blockdrop or smeltedstack with code game:toolmold-raw-axe in clay forming recipe game:recipes/clayforming/axemold.jsongame:clay-blue
23.4.2023 05:16:03 [Server Warning] Failed resolving a blocks blockdrop or smeltedstack with code game:toolmold-raw-axe in clay forming recipe game:recipes/clayforming/axemold.jsongame:clay-fire
23.4.2023 05:16:03 [Server Event] 53 clay forming recipes loaded (2 could not be resolved)
23.4.2023 05:16:03 [Server Event] 43 knapping recipes loaded
23.4.2023 05:16:03 [Server Event] 140 barrel recipes loaded
23.4.2023 05:16:03 [Server Notification] Entering runphase AssetsFinalize
23.4.2023 05:16:03 [Server Warning] Failed resolving crafting recipe ingredient with code game:debarkedlog-{wood}-ud in ground recipe indappledgroves:recipes/ground/chopping/logslab.json
23.4.2023 05:16:03 [Server Warning] Failed resolving a blocks blockdrop or smeltedstack with code indappledgroves:logslab-{wood}-debarked-down-free in ground recipe indappledgroves:recipes/ground/chopping/logslab.json
23.4.2023 05:16:03 [Server Warning] ground recipe file indappledgroves:recipes/ground/sawing/boards.json make uses of wildcards, but no blocks or item matching those wildcards were found.
23.4.2023 05:16:03 [Server Event] 131 ground recipes loaded
23.4.2023 05:16:03 [Server Warning] Failed resolving crafting recipe ingredient with code game:debarkedlog-{wood}-ud in chopping block recipe indappledgroves:recipes/choppingblock/logslab.json
23.4.2023 05:16:03 [Server Warning] Failed resolving a blocks blockdrop or smeltedstack with code indappledgroves:logslab-{wood}-debarked-down-free in chopping block recipe indappledgroves:recipes/choppingblock/logslab.json
23.4.2023 05:16:03 [Server Event] 51 chopping block recipes loaded
23.4.2023 05:16:03 [Server Warning] Failed resolving crafting recipe ingredient with code game:debarkedlog-{wood}-ud in sawbuck recipe indappledgroves:recipes/sawbuck/log.json
23.4.2023 05:16:03 [Server Warning] Failed resolving a blocks itemdrop or smeltedstack with code game:plank-{wood} in sawbuck recipe indappledgroves:recipes/sawbuck/log.json

and these ones seem to be from removing the vanilla items? unsure if there was a mapping though

23.4.2023 05:16:04 [Server Error] Cannot resolve stack randomizer item with code axe-felling-copper, wrong code?
23.4.2023 05:16:04 [Server Error] Cannot resolve stack randomizer item with code axe-felling-copper, wrong code?
23.4.2023 05:16:04 [Server Error] Cannot resolve stack randomizer item with code axe-bearded-ruined, wrong code?
23.4.2023 05:16:04 [Server Error] Cannot resolve stack randomizer item with code axe-battle-ruined, wrong code?
23.4.2023 05:16:04 [Server Error] Cannot resolve stack randomizer item with code axe-bardiche-ruined, wrong code?
23.4.2023 05:16:04 [Server Error] Cannot resolve stack randomizer item with code axe-double-ruined, wrong code?
23.4.2023 05:16:04 [Server Debug] Block simulation loaded items
23.4.2023 05:16:04 [Server Notification] Server map set
23.4.2023 05:16:04 [Server Notification] Entering runphase GameReady
23.4.2023 05:16:04 [Server Event] Starting world generators...
23.4.2023 05:16:04 [Server Notification] Entering runphase WorldReady
23.4.2023 05:16:05 [Server Warning] Block schematic file village-27.json uses items that could no longer be found. These will turn into unknown items! (affected: game:axe-felling-copper)
23.4.2023 05:16:05 [Server Warning] Block schematic file village-27.json uses items that could no longer be found. These will turn into unknown items! (affected: game:axe-felling-copper)
23.4.2023 05:16:05 [Server Warning] Block schematic file village-27.json uses items that could no longer be found. These will turn into unknown items! (affected: game:axe-felling-copper)
23.4.2023 05:16:05 [Server Warning] Block schematic file village-27.json uses items that could no longer be found. These will turn into unknown items! (affected: game:axe-felling-copper)

**Comment by VinterNacht** [comment]
Glad to see it has no errors... Truly fantastic ;)

**Comment by RogueRaiden** [comment]
lmao i hit ctrl + enter and it posted it
im getting them now

**Comment by VinterNacht** [comment]
I've probably addressed quite a few of them in the new release, so I'm looking for any stragglers.
Some errors are, unfortunately, unable to be removed.

**Comment by RogueRaiden** [comment]
probably the ones related to vanilla axes that cant be removed?

**Comment by VinterNacht** [comment]
Well, it turns out I seem to have been able to remove them. I didn't get a crash, so perhaps they made that bit a little less fragile.

**Comment by VinterNacht** [comment]
**Will Resolve These, but only to make them disappear.**
23.4.2023 05:16:03 [Server Warning] Failed resolving a blocks itemdrop or smeltedstack with code indappledgroves:adzehead-copper in smithing recipe indappledgroves:recipes/smithing/adzehead.jsongame:ingot-copper
23.4.2023 05:16:03 [Server Warning] Failed resolving a blocks itemdrop or smeltedstack with code indappledgroves:adzehead-gold in smithing recipe indappledgroves:recipes/smithing/adzehead.jsongame:ingot-gold
23.4.2023 05:16:03 [Server Warning] Failed resolving a blocks itemdrop or smeltedstack with code indappledgroves:adzehead-silver in smithing recipe indappledgroves:recipes/smithing/adzehead.jsongame:ingot-silver


**I can't get the bloody claymolding recipe to go away, so these errors are probably staying**
23.4.2023 05:16:03 [Server Warning] Failed resolving a blocks blockdrop or smeltedstack with code game:toolmold-raw-axe in clay forming recipe game:recipes/clayforming/axemold.jsongame:clay-blue
23.4.2023 05:16:03 [Server Warning] Failed resolving a blocks blockdrop or smeltedstack with code game:toolmold-raw-axe in clay forming recipe game:recipes/clayforming/axemold.jsongame:clay-fire

**I just finished fixing these:**
23.4.2023 05:16:03 [Server Warning] Failed resolving a blocks blockdrop or smeltedstack with code indappledgroves:logslab-{wood}-debarked-down-free in ground recipe indappledgroves:recipes/ground/chopping/logslab.json
23.4.2023 05:16:03 [Server Warning] Failed resolving crafting recipe ingredient with code game:debarkedlog-{wood}-ud in chopping block recipe indappledgroves:recipes/choppingblock/logslab.json
23.4.2023 05:16:03 [Server Warning] Failed resolving a blocks blockdrop or smeltedstack with code indappledgroves:logslab-{wood}-debarked-down-free in chopping block recipe indappledgroves:recipes/choppingblock/logslab.json
23.4.2023 05:16:03 [Server Event] 51 chopping block recipes loaded
23.4.2023 05:16:03 [Server Warning] Failed resolving crafting recipe ingredient with code game:debarkedlog-{wood}-ud in sawbuck recipe indappledgroves:recipes/sawbuck/log.json

**Will Look Into These**
23.4.2023 05:16:03 [Server Warning] ground recipe file indappledgroves:recipes/ground/sawing/boards.json make uses of wildcards, but no blocks or item matching those wildcards were found.
23.4.2023 05:16:03 [Server Warning] Failed resolving a blocks itemdrop or smeltedstack with code game:plank-{wood} in sawbuck recipe indappledgroves:recipes/sawbuck/log.json

**Comment by RogueRaiden** [comment]
**ahh so these errors**
23.4.2023 05:16:04 [Server Error] Cannot resolve stack randomizer item with code axe-bearded-ruined, wrong code?
23.4.2023 05:16:04 [Server Error] Cannot resolve stack randomizer item with code axe-battle-ruined, wrong code?
23.4.2023 05:16:04 [Server Error] Cannot resolve stack randomizer item with code axe-bardiche-ruined, wrong code?
23.4.2023 05:16:04 [Server Error] Cannot resolve stack randomizer item with code axe-double-ruined, wrong code?

are because in your axetweaks.json patch, you replace the metal axe variants which removes the newly added ruined bardiche, bearded, battle and double axes from the game. looks like the axe patches need to be looked at and redone

**Comment by VinterNacht** [comment]
Will be resolved in 1.18-v0.4.9-rc.4
