### ISSUE TITLE
[FGC] Brood Box Top - No Recipe in Handbook / Broken Link in Handbook

### ISSUE THREAD

**Issue by Elfinlocks** [Aetherial-Labs/Issue-Reporting#9]
The link to the Brood Box top in the Handbook doesn't seem to work, and I can't seem to see any "example" recipe for it like the others - am I just missing something?

![image](https://user-images.githubusercontent.com/43624750/235010641-b4872676-abf4-4329-b4aa-b4fc17baa316.png)

![image](https://user-images.githubusercontent.com/43624750/235010769-d4bdcb39-5a45-4544-ad93-f890510f9d26.png)

**Comment by VinterNacht** [comment]
I'm not able to repeat this issue, what version are you on?

**Comment by Elfinlocks** [comment]
My bad, this was only an issue because I was on FGC rc1, updating to rc2 resolved this - thanks!
